# Generated by Django 2.2.10 on 2021-08-20 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование валюты')),
                ('code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Код валюты')),
            ],
            options={
                'verbose_name': 'Список валюты',
            },
        ),
    ]
