# Generated by Django 2.2.10 on 2021-08-20 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencylist',
            name='date_modified',
            field=models.DateField(auto_now=True, verbose_name='Дата модификации'),
        ),
    ]
