# Generated by Django 2.2.10 on 2021-08-20 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_currencylist_date_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencylist',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата модификации'),
        ),
    ]
